[build]
  publish = "site/_site"
  command = "BUNDLE_GEMFILE=site/Gemfile bundle install && npm run bookshop-hosted && cd site && bundle exec jekyll build"
[build.environment]
  NODE_VERSION = "14.15.0"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"


