[build]
  publish = "_site"
  command = "BUNDLE_GEMFILE=site/Gemfile bundle install && BUNDLE_GEMFILE=site/Gemfile bundle exec jekyll build --source site"
[build.environment]
  NODE_VERSION = "14.15.0"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"


