[build]
  publish = "_site"
  command = "npm run-p add-netlify-url install-jekyll build-jekyll setup-service-worker"
[build.environment]
  NODE_VERSION = "14.15.0"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"


